<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT glossary (Code+, Versie+, Publicatiedatum+, Titel+, XmlLabel+, FunctioneelBlok+, Omschrijving+, ToegelatenDomein+, Referentie+, Type+, Lengte+, Aanwezigheid+, Formaat+, Anomalie+)>
     <!ELEMENT List (glossary+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Versie (#PCDATA)>
     <!ELEMENT Publicatiedatum (#PCDATA)>
     <!ELEMENT Titel (#PCDATA)>
     <!ELEMENT XmlLabel (#PCDATA)>
     <!ELEMENT FunctioneelBlok (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT ToegelatenDomein (#PCDATA)>
     <!ELEMENT Referentie (#PCDATA)>
     <!ELEMENT Type (#PCDATA)>
     <!ELEMENT Lengte (#PCDATA)>
     <!ELEMENT Aanwezigheid (#PCDATA)>
     <!ELEMENT Formaat (#PCDATA)>
     <!ELEMENT Anomalie (AnomalieCode+,AnomalieTitel+,AnomalieErnst+)>     <!ELEMENT AnomalieCode (#PCDATA)>     <!ELEMENT AnomalieTitel (#PCDATA)>     <!ELEMENT AnomalieErnst (#PCDATA)>
]>
<List>
<glossary>
<Code>00218</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>DATUM VAN CREATIE VAN HET FORMULIER</Titel><XmlLabel>FormCreationDate</XmlLabel><FunctioneelBlok>Formulier</FunctioneelBlok><Omschrijving>
Datum waarop het formulier gecreëerd is.</Omschrijving><ToegelatenDomein>
JJJJ is een element van [lopend jaar -1 ; lopend jaar] ;
De datum mag zich niet in de toekomst bevinden.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>10</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>JJJJ-MM-DD
· JJJJ is het jaar
· MM is de maand
. DD is de dag</Formaat><Anomalie><AnomalieCode>00218-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00218-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00218-003</AnomalieCode><AnomalieTitel>Ongeldig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00218-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00218-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00218-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00298</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>HERKOMST VAN DE REFERENTIE</Titel><XmlLabel>ReferenceOrigin</XmlLabel><FunctioneelBlok>Referentie</FunctioneelBlok><Omschrijving>Waarde die de authentieke bron van een referentienummer aanduidt.
</Omschrijving><ToegelatenDomein>1 = het referentienummer is toegekend door een aangever of aanvrager (een bedrijf, een sociaal secretariaat, een softwareontwikkelaar, ...)
2 = het ticketnummer toegekend door de sociale zekerheid, dat een aangifte, een aanvraag of een antwoord op eenduidige wijze identificeert
3 = het referentienummer is toegekend door een sector van de sociale zekerheid
4 = het referentienummer is toegekend door de dienst ePost
5 = het referentienummer is toegekend door de KSZ
6 = het referentienummer is toegekend door het archiveringssysteem (DOC-ID)
7 = het referentienummer is door de DSP aan een gearchiveerd document toegekend (DSP-ID)
1 of 2 voor DmfAPID</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>1</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00298-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00298-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00298-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00298-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00298-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00298-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00296</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>IDENTIFICATIE VAN HET FORMULIER</Titel><XmlLabel>Identification</XmlLabel><FunctioneelBlok>Formulier</FunctioneelBlok><Omschrijving>Zone die de inhoud van een formulier beschrijft.
</Omschrijving><ToegelatenDomein>Zie bijlage 11 - Identificatie van het formulier.
DmfAPID voor het bericht met de identificatiegegevens van een oorspronkelijk DmfA aangifte</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>7</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00296-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00296-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00296-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00296-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00296-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00024</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>IDENTIFICATIENUMMER BIJ DE SOCIALE ZEKERHEID - INSZ</Titel><XmlLabel>INSS</XmlLabel><FunctioneelBlok>Identificatie van de natuurlijke persoon</FunctioneelBlok><Omschrijving>Identificatienummer van een natuurlijk persoon binnen de sociale zekerheid. Dit is het identificatienummer van de natuurlijke persoon in het rijksregister of in het bisregister van de natuurlijke personen.
</Omschrijving><ToegelatenDomein>De vermelde waarde mag niet nul zijn.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>11</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>0 of NNNNNNNNNCC
· NNNNNNNNN is het nummer
· CC is het controlegetal.</Formaat><Anomalie><AnomalieCode>00024-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00024-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00024-003</AnomalieCode><AnomalieTitel>Ongeldig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00024-004</AnomalieCode><AnomalieTitel>Ongeldig controlegetal</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00024-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00024-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00013</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>JAAR - KWARTAAL</Titel><XmlLabel>Quarter</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving>Bepaling van het jaar en het kwartaal.
Bepaling van het jaar en het kwartaal van de aangifte.</Omschrijving><ToegelatenDomein>Het moet gelegen zijn tussen het eerste kwartaal 2003 (20031) en het laatste afgelopen kalenderkwartaal (lopend JJJJK -1).</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>5</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>JJJJK
. JJJJ is het jaar
. K is het kwartaal</Formaat><Anomalie><AnomalieCode>00013-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-003</AnomalieCode><AnomalieTitel>Ongeldig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00013-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00493</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>NAAM VAN DE WERKNEMER ZOALS GEDECLAREERD IN DE ORIGINELE AANGIFTE</Titel><XmlLabel>OriginalDeclaredWorkerName</XmlLabel><FunctioneelBlok>Identificatie van de natuurlijke persoon</FunctioneelBlok><Omschrijving>Familienaam van een natuurlijk persoon zoals opgegeven in de oorspronkelijk aangifte 
</Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>48</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00493-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00493-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00493-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00012</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>NOTIE CURATELE</Titel><XmlLabel>Trusteeship</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving>Code die aanduidt of de aangifte al dan niet betrekking heeft op een periode onder curatele.Deze zone wordt nooit vermeld als het gaat omeen provinciaal of plaatselijk bestuur.</Omschrijving><ToegelatenDomein>0 = periode niet onder curatele
1 = periode onder curatele</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>1</Lengte><Aanwezigheid>Verplicht indien het gaat om een DmfA.</Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00012-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00012-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00012-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00012-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00012-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00012-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00781</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>NUMMERPLAAT</Titel><XmlLabel>LicensePlate</XmlLabel><FunctioneelBlok>Identificatie van het bedrijfsvoertuig</FunctioneelBlok><Omschrijving>Nummerplaat van een voertuig bij de DIV</Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>10</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00781-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00014</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>ONDERNEMINGSNUMMER</Titel><XmlLabel>CompanyID</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving>Nummer dat een werkgever eenduidig identificeert, of het nu gaat om een natuurlijk persoon, een groepering van natuurlijke personen of een rechtspersoon.
</Omschrijving><ToegelatenDomein>
Getal van 10 cijfers waarvan :
de posities 1 tot 8 overeenkomen met een volgnummer, met op de eerste positie een cijfer gelijk aan nul of 1;
de posities 9 en 10 overeenkomen met een controlegetal.
Als het ondernemingsnummer niet gekend is, dient de waarde nul meegedeeld te worden.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>10</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00014-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00014-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00014-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00014-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00014-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00548</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>PERMANENTE IDENTIFICATIECODE VAN DE AANGEGEVEN NATUURLIJKE PERSOON</Titel><XmlLabel>DeclNaturalPersonPID</XmlLabel><FunctioneelBlok>Identificatie van de natuurlijke persoon</FunctioneelBlok><Omschrijving>Permanente identificatiecode van de natuurlijke persoon binnen een aangifte toegekend door de sociale zekerheid.</Omschrijving><ToegelatenDomein>[1;99999999999]</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>11</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00548-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00548-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00548-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00548-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00549</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>PERMANENTE IDENTIFICATIECODE VAN DE NATUURLIJKE PERSOON</Titel><XmlLabel>NaturalPersonPID</XmlLabel><FunctioneelBlok>Identificatie van de natuurlijke persoon</FunctioneelBlok><Omschrijving>Permanente identificatiecode van de natuurlijke persoon toegekend door de sociale zekerheid</Omschrijving><ToegelatenDomein>[1;99999999999]</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>11</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00549-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00549-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00549-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00549-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00534</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>PERMANENTE IDENTIFICATIECODE VAN DE WERKGEVERSAANGIFTE</Titel><XmlLabel>EmployerDeclarationPID</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving>Permanente identificatiecode van de aangifte van de werkgever toegekend door de sociale zekerheid</Omschrijving><ToegelatenDomein>[1;99999999999]</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>11</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00534-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00534-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00534-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00534-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00534-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00534-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00109</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>PPL NUMMER</Titel><XmlLabel>NOSSLPARegistrationNbr</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving> Elke lokale of provinciale overheid die personeel in dienst heeft, moet ingeschreven zijn bij de RSZ.Deze zone wordt nooit vermeld als het gaat om een DmfA.</Omschrijving><ToegelatenDomein>Geheel getal en element van [00000197;99999926]. Als het uniek ondernemingsnummer gekend is (zone 00014 verschillend van nul), kan het PPL nummer op de waarde nul gezet worden.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>8</Lengte><Aanwezigheid>Verplicht indien het gaat om een DmfAPPL.</Aanwezigheid><Formaat>0 of NNNNNNCC
· NNNNNN is het nummer
· CC is het controlegetal.</Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00299</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>PRECIES UUR VAN CREATIE VAN HET FORMULIER</Titel><XmlLabel>FormCreationHour</XmlLabel><FunctioneelBlok>Formulier</FunctioneelBlok><Omschrijving>Tijdstip, uitgedrukt in uren, minuten, seconden en milliseconden.
</Omschrijving><ToegelatenDomein>UU is een element van [00;23]
MM is een element van [00;59]
SS is een element van [00;59]
SSS is een element van [000;999]
</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>12</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>UU:MM:SS.SSS
. UU zijn de uren
. MM zijn de minuten
. SS zijn de seconden
. SSS zijn de milliseconden</Formaat><Anomalie><AnomalieCode>00299-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00299-003</AnomalieCode><AnomalieTitel>Ongeldig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00299-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00299-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00299-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00615</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>REFERENTIE GEBRUIKER - NATUURLIJKE PERSOON</Titel><XmlLabel>NaturalPersonUserReference</XmlLabel><FunctioneelBlok>Identificatie van de natuurlijke persoon</FunctioneelBlok><Omschrijving>Referentie.
Referentie van de natuurlijke persoon gebruikt door de werkgever of een erkend sociaal secretariaat.</Omschrijving><ToegelatenDomein>In dit bericht is de toegelaten lengte voor deze zone 20 tekens.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>200</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00615-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00615-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00615-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00617</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>REFERENTIE GEBRUIKER - TEWERKSTELLING VAN DE WERKNEMERSLIJN</Titel><XmlLabel>OccupationUserReference</XmlLabel><FunctioneelBlok>Identificatie van de tewerkstelling</FunctioneelBlok><Omschrijving>Referentie.
Referentie van de Tewerkstelling van de werknemerslijn gebruikt door de werkgever of een erkend sociaal secretariaat.</Omschrijving><ToegelatenDomein>In dit bericht is de toegelaten lengte voor deze zone 20 tekens.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>200</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00617-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00617-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00617-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00616</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>REFERENTIE GEBRUIKER - WERKNEMERSLIJN</Titel><XmlLabel>WorkerRecordUserReference</XmlLabel><FunctioneelBlok>Identificatie van de werknemerslijn - PID</FunctioneelBlok><Omschrijving>Referentie.
Referentie van de werknemerslijn gebruikt door de werkgever of een erkend sociaal secretariaat.</Omschrijving><ToegelatenDomein>In dit bericht is de toegelaten lengte voor deze zone 20 tekens.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>200</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00616-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00616-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00616-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00222</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>REFERENTIENUMMER</Titel><XmlLabel>ReferenceNbr</XmlLabel><FunctioneelBlok>Referentie</FunctioneelBlok><Omschrijving>Het referentienummer.</Omschrijving><ToegelatenDomein>In dit bericht is de toegelaten lengte voor deze zone 20 tekens.
Het Smals-ticketnummer dat toegekend werd aan de bijbehorende DMFA.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>64</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00222-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00222-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00222-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00222-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00222-191</AnomalieCode><AnomalieTitel>Identificatie van het formulier waarnaar dit ticketnummer verwijst, behoort niet tot het verwachte type</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00011</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>RSZ-NUMMER</Titel><XmlLabel>NOSSRegistrationNbr</XmlLabel><FunctioneelBlok>Identificatie van de Werkgeversaangifte</FunctioneelBlok><Omschrijving>Iedere werkgever, of het nu een natuurlijke persoon, een groepering van natuurlijke personen of een rechtspersoon betreft, die personeel in dienst heeft dat onderworpen is aan de wet van 27 juni 1969, moet ingeschreven zijn bij de RSZ. Het gaat om een definitief RSZ-nummer.
Deze zone wordt nooit vermeld als het gaat om een provinciaal of plaatselijk bestuur.</Omschrijving><ToegelatenDomein>Geheel getal en element van [100006;199999934] voor de definitieve nummers.
Als het uniek ondernemingsnummer gekend is (zone 00014 verschillend van nul), kan het RSZ-nummer op de waarde nul gezet worden.
In het glossarium DmfAPID de waarde "0" is niet toegelaten</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>9</Lengte><Aanwezigheid>Verplicht indien het gaat om een DmfA.</Aanwezigheid><Formaat>0 of NNNNNNNCC
· NNNNNNN is het nummer
· CC is het controlegetal.</Formaat><Anomalie><AnomalieCode>00011-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00011-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00011-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00011-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00011-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00110</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>STATUS VAN HET ATTEST</Titel><XmlLabel>AttestationStatus</XmlLabel><FunctioneelBlok>Formulier</FunctioneelBlok><Omschrijving></Omschrijving><ToegelatenDomein>0 = Origineel
1 = Wijziging
2 = Duplicaat
3 = Annulatie
4 = Herziening
5 = Herinnering
6 = Afsluiting
7 = Wijziging van papieren origineel
8 = Kopie</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>1</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00110-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00110-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00110-008</AnomalieCode><AnomalieTitel>Niet in het toegelaten domein</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00110-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00110-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00110-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00043</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>TEWERKSTELLINGSNUMMER</Titel><XmlLabel>OccupationSequenceNbr</XmlLabel><FunctioneelBlok>Identificatie van de tewerkstelling</FunctioneelBlok><Omschrijving>Volgnummer van de tewerkstellingen binnen een werknemerslijn.
Dit nummer moet uniek zijn binnen een werknemerslijn.</Omschrijving><ToegelatenDomein>Positief geheel getal en element van [1;99].Het volgnummer van de tewerkstelling moet overeenstemmen met het oorspronkelijk aangegeven volgnummer.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode>00043-001</AnomalieCode><AnomalieTitel>Niet aanwezig</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00043-002</AnomalieCode><AnomalieTitel>Niet numeriek</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00043-093</AnomalieCode><AnomalieTitel>Foutieve lengte</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00043-090</AnomalieCode><AnomalieTitel>Fout op kardinaliteit</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie><Anomalie><AnomalieCode>00043-146</AnomalieCode><AnomalieTitel>Niet toegelaten</AnomalieTitel><AnomalieErnst>B</AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00221</Code><Versie>2023/2</Versie><Publicatiedatum></Publicatiedatum><Titel>TYPE VAN DE REFERENTIE</Titel><XmlLabel>ReferenceType</XmlLabel><FunctioneelBlok>Referentie</FunctioneelBlok><Omschrijving>Duidt aan naar waar de referentie (00222 Referentienummer) verwijst: naar deze aangifte, naar een aangifte die verwant is met deze aangifte of naar een verzameling aangiften (= een dossier) waar deze aangifte toe behoort, op deze aanvraag, op dit formulier.</Omschrijving><ToegelatenDomein>0 = de referentie heeft betrekking op een eerder uitgewisseld formulier dat niet dezelfde identificatie heeft (zie bijlagen 11/302), dat verband houdt met het huidige formulier
1 = de referentie verwijst naar dit formulier
2 = de referentie is een dossiernummer en verwijst naar het dossier (= verzameling van aangiften) waartoe deze aangifte behoort of waartoe dit formulier behoort