<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT glossary (Code+, Versie+, Publicatiedatum+, Titel+, XmlLabel+, FunctioneelBlok+, Omschrijving+, ToegelatenDomein+, Referentie+, Type+, Lengte+, Aanwezigheid+, Formaat+, Anomalie+)>
     <!ELEMENT List (glossary+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Versie (#PCDATA)>
     <!ELEMENT Publicatiedatum (#PCDATA)>
     <!ELEMENT Titel (#PCDATA)>
     <!ELEMENT XmlLabel (#PCDATA)>
     <!ELEMENT FunctioneelBlok (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT ToegelatenDomein (#PCDATA)>
     <!ELEMENT Referentie (#PCDATA)>
     <!ELEMENT Type (#PCDATA)>
     <!ELEMENT Lengte (#PCDATA)>
     <!ELEMENT Aanwezigheid (#PCDATA)>
     <!ELEMENT Formaat (#PCDATA)>
     <!ELEMENT Anomalie (AnomalieCode+,AnomalieTitel+,AnomalieErnst+)>     <!ELEMENT AnomalieCode (#PCDATA)>     <!ELEMENT AnomalieTitel (#PCDATA)>     <!ELEMENT AnomalieErnst (#PCDATA)>
]>
<List>
<glossary>
<Code>01075</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>AANTAL DAGEN VERTRAGING</Titel><XmlLabel>DelayDaysNbr</XmlLabel><FunctioneelBlok>Boeking - Detail</FunctioneelBlok><Omschrijving>Aantal dagen vertraging</Omschrijving><ToegelatenDomein>[0,99999]</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>5</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01077</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>AARD VAN DE BOEKING</Titel><XmlLabel>AccountingEntryNature</XmlLabel><FunctioneelBlok>Lijst van de bedragen</FunctioneelBlok><Omschrijving>Zone die toelaat de aard (rechtvaardiging) van de boeking te preciseren.</Omschrijving><ToegelatenDomein>1 = Bijdragen
2 = Bijdrageopslagen 
3 = Interesten</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01098</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>BESLISSING OVER DE BETALINGSTERMIJN</Titel><XmlLabel>PaymentTermDecision</XmlLabel><FunctioneelBlok>Boeking - Informatie</FunctioneelBlok><Omschrijving>Zone die de beslissing over de betalingstermijn bevat.</Omschrijving><ToegelatenDomein>1 = Weigering (de werkgever heeft er geen recht op)
2 = Toekenning (de werkgever heeft een termijn gekregen)
3 = In verwerking (de RSZ heeft nog niet beslist)</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>1</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01070</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>BETALINGSTERMIJN</Titel><XmlLabel>PaymentTerm</XmlLabel><FunctioneelBlok>Boeking - Informatie</FunctioneelBlok><Omschrijving>Zone waarin men kan preciseren welk type termijn van toepassing is op de werkgever voor het kwartaal.</Omschrijving><ToegelatenDomein>1 = Wettelijke termijn
2 = Reglementaire termijn
3 = Covid termijn</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Verboden </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01072</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>BOEKHOUDKUNDIG GROEPERINGSNUMMER</Titel><XmlLabel>AccountingBulkingNbr</XmlLabel><FunctioneelBlok>Boeking - Informatie</FunctioneelBlok><Omschrijving>Volgnummer verbonden aan de periode waarvoor de boeking wordt opgesteld.</Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01071</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>BOEKHOUDKUNDIGE GROEPERING</Titel><XmlLabel>AccountingBulking</XmlLabel><FunctioneelBlok>Boeking - Informatie</FunctioneelBlok><Omschrijving>Type periode waarvoor de boeking wordt opgesteld.</Omschrijving><ToegelatenDomein>0 = jaarlijkse vakantie 
1 = WB (wijzigend bericht) jaarlijkse vakantie
2 = basisperiode en bijlage aangifte
3 = WB (wijzigend bericht) basisperiode en bijlage aangifte
4 = debetbericht economische werkloosheid
5 = debetbericht Vorming
6 = debetbericht art. 22Qter</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01068</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>DAGELIJKSE INTERESTEN</Titel><XmlLabel>DailyInterests</XmlLabel><FunctioneelBlok>Herinnering - Informatie</FunctioneelBlok><Omschrijving>Bedrag van de dagelijkse interesten</Omschrijving><ToegelatenDomein>[0,999999999999999]
Het bedrag wordt uitgedrukt in eurocenten.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>15</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00872</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>DATUM - BOEKHOUDKUNDIGE DATUM</Titel><XmlLabel>AccountingDate</XmlLabel><FunctioneelBlok>Boeking - Detail</FunctioneelBlok><Omschrijving></Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>10</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>JJJJ-MM-DD
· JJJJ is het jaar
· MM is de maand
. DD is de dag</Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01066</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>DATUM VAN AFSLUITING</Titel><XmlLabel>ClosingDate</XmlLabel><FunctioneelBlok>Herinnering - Informatie</FunctioneelBlok><Omschrijving>
Datum van afsluitingDatum waarop het rekeninguittreksel werd afgesloten.
Deze zone komt overeen met de afsluitingsdatum van de rekening van het initiële type herinnering C398. </Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>10</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>JJJJ-MM-DD
· JJJJ is het jaar
· MM is de maand
. DD is de dag</Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01166</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>DATUM VAN AFSLUITING VAN HET ORIGINELE DOCUMENT</Titel><XmlLabel>OriginalClosingDate</XmlLabel><FunctioneelBlok>Herinnering - Informatie</FunctioneelBlok><Omschrijving>
Datum van afsluiting van het originele document.Deze zone komt overeen met de afsluitingsdatum van de rekening van het type herinnering C398 vermeld in het document C398DW.</Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>10</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat>JJJJ-MM-DD
· JJJJ is het jaar
· MM is de maand
. DD is de dag</Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01078</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>GETEKEND BEDRAG</Titel><XmlLabel>SignedAmount</XmlLabel><FunctioneelBlok>Lijst van de bedragen</FunctioneelBlok><Omschrijving>Getekend bedrag</Omschrijving><ToegelatenDomein>Het bedrag wordt uitgedrukt in eurocenten.</ToegelatenDomein><Referentie></Referentie><Type>Alfanumeriek</Type><Lengte>16</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01076</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>GLOBAAL BEDRAG</Titel><XmlLabel>GlobalAmount</XmlLabel><FunctioneelBlok>Boeking - Detail</FunctioneelBlok><Omschrijving>Globaal bedrag van een betaling die opgesplitst werd in verschillende boekingen.</Omschrijving><ToegelatenDomein>[0,999999999999999]
Het bedrag wordt uitgedrukt in eurocenten.</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>15</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01074</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>HERKOMST VAN DE BOEKING</Titel><XmlLabel>AccountingEntryOrigin</XmlLabel><FunctioneelBlok>Boeking - Detail</FunctioneelBlok><Omschrijving>Zone die toelaat de herkomst van de boeking te identificeren.</Omschrijving><ToegelatenDomein>1 = Betaling - ESS Verdeellijst
2 = Betaling - Andere
3 = Werkgever/ ESS
4 = RSZ</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>00866</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>KWARTAAL VAN BOEKING</Titel><XmlLabel>AccountingQuarter</XmlLabel><FunctioneelBlok>Boeking - Informatie</FunctioneelBlok><Omschrijving></Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>5</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat>JJJJK
. JJJJ is het jaar
. K is het kwartaal</Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01069</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>PROCEDURENUMMER</Titel><XmlLabel>ProcedureNbr</XmlLabel><FunctioneelBlok>Herinnering - Informatie</FunctioneelBlok><Omschrijving>ProcedurenummerDit is het nummer van de procedure die verband houdt met de boekingen waarop de herinnering betrekking heeft.</Omschrijving><ToegelatenDomein></ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>4</Lengte><Aanwezigheid>Facultatief </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01073</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>TYPE BOEKING</Titel><XmlLabel>AccountingEntryType</XmlLabel><FunctioneelBlok>Boeking - Detail</FunctioneelBlok><Omschrijving>Zone die toelaat het type boeking te identificeren.</Omschrijving><ToegelatenDomein>Cf. specifieke bijlage FinancialState01 : Beschrijving van de boekoudkundige referenties</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
<glossary>
<Code>01067</Code><Versie>2023/3</Versie><Publicatiedatum>31/08/2023</Publicatiedatum><Titel>TYPE HERINNERING</Titel><XmlLabel>ReminderType</XmlLabel><FunctioneelBlok>Herinnering - Informatie</FunctioneelBlok><Omschrijving>Zone die toelaat het type herinnering te identificeren.</Omschrijving><ToegelatenDomein>1 = laatste herinnering voor invervolgingstelling (C397)
2 = herinnering betreffende invervolgingstelling (C398)
3 = geactualiseerde herinnering betreffende invervolgingstelling (C398DW)
4 = geactualiseerde laatste herinnering voor invervolgingstelling (C397)</ToegelatenDomein><Referentie></Referentie><Type>Numeriek</Type><Lengte>2</Lengte><Aanwezigheid>Onmisbaar </Aanwezigheid><Formaat></Formaat><Anomalie><AnomalieCode></AnomalieCode><AnomalieTitel></AnomalieTitel><AnomalieErnst></AnomalieErnst></Anomalie>
</glossary>
</List>
