<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann1 (Naam?, Code?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann1+)>
     <!ELEMENT Naam (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann1>
<Naam>'S GRAVENBRAKEL</Naam>
<Code>55004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AALST</Naam>
<Code>41002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AALTER</Naam>
<Code>44001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2018</einde_geldigheid>
</ann1>
<ann1>
<Naam>AALTER</Naam>
<Code>44084</Code>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AARLEN</Naam>
<Code>81001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AARSCHOT</Naam>
<Code>24001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AARTSELAAR</Naam>
<Code>11001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AAT</Naam>
<Code>51004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AFFLIGEM</Naam>
<Code>23105</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AISEAU-PRESLES</Naam>
<Code>52074</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ALKEN</Naam>
<Code>73001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ALVERINGEM</Naam>
<Code>38002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AMAY</Naam>
<Code>61003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AMEL</Naam>
<Code>63001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANDENNE</Naam>
<Code>92003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANDERLECHT</Naam>
<Code>21001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANDERLUES</Naam>
<Code>56001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANHEE</Naam>
<Code>91005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANS</Naam>
<Code>62003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANTHISNES</Naam>
<Code>61079</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANTOING</Naam>
<Code>57003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANTWERPEN</Naam>
<Code>11002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ANZEGEM</Naam>
<Code>34002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ARDOOIE</Naam>
<Code>37020</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ARENDONK</Naam>
<Code>13001</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AS</Naam>
<Code>71002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ASSE</Naam>
<Code>23002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ASSENEDE</Naam>
<Code>43002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ASSESSE</Naam>
<Code>92006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ATTERT</Naam>
<Code>81003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AUBANGE</Naam>
<Code>81004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AUBEL</Naam>
<Code>63003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AVELGEM</Naam>
<Code>34003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AWANS</Naam>
<Code>62006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>AYWAILLE</Naam>
<Code>62009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BAARLE-HERTOG</Naam>
<Code>13002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BAELEN</Naam>
<Code>63004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BALEN</Naam>
<Code>13003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BASTENAKEN</Naam>
<Code>82003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEAUMONT</Naam>
<Code>56005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEAURAING</Naam>
<Code>91013</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEERNEM</Naam>
<Code>31003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEERSE</Naam>
<Code>13004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEERSEL</Naam>
<Code>23003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEGIJNENDIJK</Naam>
<Code>24007</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEKKEVOORT</Naam>
<Code>24008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BELOEIL</Naam>
<Code>51008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERGEN</Naam>
<Code>53053</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERINGEN</Naam>
<Code>71004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERLAAR</Naam>
<Code>12002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERLARE</Naam>
<Code>42003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERLOZ</Naam>
<Code>64008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERNISSART</Naam>
<Code>51009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERTEM</Naam>
<Code>24009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERTOGNE</Naam>
<Code>82005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BERTRIX</Naam>
<Code>84009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEVEKOM</Naam>
<Code>25005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEVER</Naam>
<Code>23009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEVEREN</Naam>
<Code>46003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BEYNE-HEUSAY</Naam>
<Code>62015</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BIERBEEK</Naam>
<Code>24011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BIEVRE</Naam>
<Code>91015</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BILZEN</Naam>
<Code>73006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BINCHE</Naam>
<Code>56011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2018</einde_geldigheid>
</ann1>
<ann1>
<Naam>BINCHE</Naam>
<Code>58002</Code>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BITSINGEN</Naam>
<Code>62011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BLANKENBERGE</Naam>
<Code>31004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BLEGNY</Naam>
<Code>62119</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOCHOLT</Naam>
<Code>72003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOECHOUT</Naam>
<Code>11004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BONHEIDEN</Naam>
<Code>12005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOOM</Naam>
<Code>11005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOORTMEERBEEK</Naam>
<Code>24014</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BORGLOON</Naam>
<Code>73009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BORGWORM</Naam>
<Code>64074</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BORNEM</Naam>
<Code>12007</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BORSBEEK</Naam>
<Code>11007</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOUILLON</Naam>
<Code>84010</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOUSSU</Naam>
<Code>53014</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BOUTERSEM</Naam>
<Code>24016</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRAIVES</Naam>
<Code>64015</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRAKEL</Naam>
<Code>45059</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRASSCHAAT</Naam>
<Code>11008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRECHT</Naam>
<Code>11009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BREDENE</Naam>
<Code>35002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BREE</Naam>
<Code>72004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRUGELETTE</Naam>
<Code>51012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRUGGE</Naam>
<Code>31005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRUNEHAUT</Naam>
<Code>57093</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BRUSSEL</Naam>
<Code>21004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BUGGENHOUT</Naam>
<Code>42004</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BULLINGEN</Naam>
<Code>63012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BURDINNE</Naam>
<Code>61010</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BURG-REULAND</Naam>
<Code>63087</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>BUTGENBACH</Naam>
<Code>63013</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CELLES</Naam>
<Code>57018</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CERFONTAINE</Naam>
<Code>93010</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHAPELLE-LEZ-HERLAIMONT</Naam>
<Code>52010</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHARLEROI</Naam>
<Code>52011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHASTRE</Naam>
<Code>25117</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHATELET</Naam>
<Code>52012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHAUDFONTAINE</Naam>
<Code>62022</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHAUMONT-GISTOUX</Naam>
<Code>25018</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHIEVRES</Naam>
<Code>51014</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHIMAY</Naam>
<Code>56016</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CHINY</Naam>
<Code>85007</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CINEY</Naam>
<Code>91030</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CLAVIER</Naam>
<Code>61012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>COLFONTAINE</Naam>
<Code>53082</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>COMBLAIN-AU-PONT</Naam>
<Code>62026</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>COURCELLES</Naam>
<Code>52015</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>COURT-SAINT-ETIENNE</Naam>
<Code>25023</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>COUVIN</Naam>
<Code>93014</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>CRISNEE</Naam>
<Code>64021</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DALHEM</Naam>
<Code>62027</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DAMME</Naam>
<Code>31006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DAVERDISSE</Naam>
<Code>84016</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DE HAAN</Naam>
<Code>35029</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DE PANNE</Naam>
<Code>38008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DE PINTE</Naam>
<Code>44012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DEERLIJK</Naam>
<Code>34009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DEINZE</Naam>
<Code>44011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2018</einde_geldigheid>
</ann1>
<ann1>
<Naam>DEINZE</Naam>
<Code>44083</Code>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DENDERLEEUW</Naam>
<Code>41011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DENDERMONDE</Naam>
<Code>42006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DENTERGEM</Naam>
<Code>37002</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DESSEL</Naam>
<Code>13006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DESTELBERGEN</Naam>
<Code>44013</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DIEPENBEEK</Naam>
<Code>71011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DIEST</Naam>
<Code>24020</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DIKSMUIDE</Naam>
<Code>32003</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DILBEEK</Naam>
<Code>23016</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DILSEN-STOKKEM</Naam>
<Code>72041</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DINANT</Naam>
<Code>91034</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DISON</Naam>
<Code>63020</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DOISCHE</Naam>
<Code>93018</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DONCEEL</Naam>
<Code>64023</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DOORNIK</Naam>
<Code>57081</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DOUR</Naam>
<Code>53020</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DROGENBOS</Naam>
<Code>23098</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DUFFEL</Naam>
<Code>12009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>DURBUY</Naam>
<Code>83012</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ECAUSSINES</Naam>
<Code>55050</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EDEGEM</Naam>
<Code>11013</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EDINGEN</Naam>
<Code>55010</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2018</einde_geldigheid>
</ann1>
<ann1>
<Naam>EDINGEN</Naam>
<Code>51067</Code>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EEKLO</Naam>
<Code>43005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EGHEZEE</Naam>
<Code>92035</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EIGENBRAKEL</Naam>
<Code>25014</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ELSENE</Naam>
<Code>21009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ELZELE</Naam>
<Code>51017</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ENGIS</Naam>
<Code>61080</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EREZEE</Naam>
<Code>83013</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ERPE-MERE</Naam>
<Code>41082</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ERQUELINNES</Naam>
<Code>56022</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ESNEUX</Naam>
<Code>62032</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ESSEN</Naam>
<Code>11016</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ESTAIMPUIS</Naam>
<Code>57027</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ESTINNES</Naam>
<Code>56085</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2018</einde_geldigheid>
</ann1>
<ann1>
<Naam>ESTINNES</Naam>
<Code>58003</Code>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ETALLE</Naam>
<Code>85009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>ETTERBEEK</Naam>
<Code>21005</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EUPEN</Naam>
<Code>63023</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EVERE</Naam>
<Code>21006</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>EVERGEM</Naam>
<Code>44019</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FAIMES</Naam>
<Code>64076</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FARCIENNES</Naam>
<Code>52018</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FAUVILLERS</Naam>
<Code>82009</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FERNELMONT</Naam>
<Code>92138</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FERRIERES</Naam>
<Code>61019</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FEXHE-LE-HAUT-CLOCHER</Naam>
<Code>64025</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLEMALLE</Naam>
<Code>62120</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLERON</Naam>
<Code>62038</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLEURUS</Naam>
<Code>52021</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLOREFFE</Naam>
<Code>92045</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLORENNES</Naam>
<Code>93022</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FLORENVILLE</Naam>
<Code>85011</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FONTAINE-L'EVEQUE</Naam>
<Code>52022</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FOSSES-LA-VILLE</Naam>
<Code>92048</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FRAMERIES</Naam>
<Code>53028</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FRASNES-LEZ-ANVAING</Naam>
<Code>51065</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>FROIDCHAPELLE</Naam>
<Code>56029</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GALMAARDEN</Naam>
<Code>23023</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GANSHOREN</Naam>
<Code>21008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GAVERE</Naam>
<Code>44020</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GEDINNE</Naam>
<Code>91054</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GEEL</Naam>
<Code>13008</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann1>
<ann1>
<Naam>GEER</Naam>
<Code>64029</Code>
<begin_geldigheid>01/01/1900</begin_geldigheid>