<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann26 (Code?, Omschrijving?, CategorieNL?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann26+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT CategorieNL (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann26>
<Code>100</Code>
<Omschrijving>Aanvullend Paritair Comité voor de werklieden</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>101</Code>
<Omschrijving>Nationale Gemengde Mijncommissie</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102</Code>
<Omschrijving>Paritair Comité voor het groefbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.01</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der hardsteengroeven en der groeven van uit te houwen kalksteen in de provincie Henegouwen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.02</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der hardsteengroeven en der groeven van uit te houwen kalksteen in de provincies Luik en Namen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.03</Code>
<Omschrijving>Paritair Subcomité voor de porfiergroeven in de provincies Waals-Brabant en Henegouwen en de kwartsietgroeven in de provincie Waals-Brabant</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.04</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf van de zandsteen- en kwartsietgroeven op het gehele grondgebied van het Rijk, uitgezonderd de kwartsietgroeven van de provincie Waals-Brabant</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.05</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der porseleinaarde- en zandgroeven welke in openlucht geëxploiteerd worden in de provincies Waals-Brabant, Henegouwen, Luik, Luxemburg en Namen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.06</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der grint- en zandgroeven welke in openlucht geëxploiteerd worden in de provincies Antwerpen, West-Vlaanderen, Oost-Vlaanderen, Limburg en Vlaams-Brabant</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.07</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der kalksteengroeven, cementfabrieken en kalkovens van het administratief arrondissement Doornik</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.08</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der marmergroeven en -zagerijen op het gehele grondgebied van het Rijk</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.09</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf van de groeven van niet uit te houwen kalksteen en van de kalkovens, van de bitterspaatgroeven en -ovens op het gehele grondgebied van het Rijk</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.10</Code>
<Omschrijving>Paritair Subcomité voor de terugwinning van steenstort (niet samengesteld, omdat de voorzitter, de ondervoorzitter en de leden niet werden benoemd)</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>102.11</Code>
<Omschrijving>Paritair Subcomité voor het bedrijf der leisteengroeven, coticulegroeven en groeven van slijpsteen voor scheermessen in de provincies Waals-Brabant, Henegouwen, Luik, Luxemburg en Namen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>104</Code>
<Omschrijving>Paritair Comité voor de ijzernijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>105</Code>
<Omschrijving>Paritair Comité voor de non-ferro metalen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>106</Code>
<Omschrijving>Paritair Comité voor het cementbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>106.01</Code>
<Omschrijving>Paritair Subcomité voor de cementfabrieken</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>106.02</Code>
<Omschrijving>Paritair Subcomité voor de betonindustrie</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>106.03</Code>
<Omschrijving>Paritair Subcomité voor de vezelcement</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>107</Code>
<Omschrijving>Paritair Comité voor de meester-kleermakers, de kleermaaksters en naaisters</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>109</Code>
<Omschrijving>Paritair Comité voor het kleding- en confectiebedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>110</Code>
<Omschrijving>Paritair Comité voor de textielverzorging</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>111</Code>
<Omschrijving>Paritair Comité voor de metaal-, machine- en elektrische bouw</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>112</Code>
<Omschrijving>Paritair Comité voor het garagebedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>113</Code>
<Omschrijving>Paritair Comité voor het ceramiekbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>113.01</Code>
<Omschrijving>Paritair Subcomité voor het faience- en het porseleinbedrijf, de sanitaire artikelen en de schuurproducten en het ceramisch aardewerk</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2009</einde_geldigheid>
</ann26>
<ann26>
<Code>113.02</Code>
<Omschrijving>Paritair Subcomité voor de ondernemingen voor ceramiekbekleding en vloertegels</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2009</einde_geldigheid>
</ann26>
<ann26>
<Code>113.03</Code>
<Omschrijving>Paritair Subcomité voor vuurvaste producten</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2009</einde_geldigheid>
</ann26>
<ann26>
<Code>113.04</Code>
<Omschrijving>Paritair Subcomité voor de pannenbakkerijen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>114</Code>
<Omschrijving>Paritair Comité voor de steenbakkerij</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>114.01</Code>
<Omschrijving>Paritair Subcomité voor de steenbakkerij van de provincies Oost- en West-Vlaanderen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2013</einde_geldigheid>
</ann26>
<ann26>
<Code>114.02</Code>
<Omschrijving>Paritair Subcomité voor de steenbakkerij van de provincie Antwerpen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2013</einde_geldigheid>
</ann26>
<ann26>
<Code>114.03</Code>
<Omschrijving>Paritair Subcomité voor de steenbakkerij van de provincie Limburg en van Vlaams-Brabant</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2013</einde_geldigheid>
</ann26>
<ann26>
<Code>114.04</Code>
<Omschrijving>Paritair Subcomité voor de steenbakkerij van de provincies Luik, Luxemburg, Namen en Henegouwen en van Waals-Brabant</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2013</einde_geldigheid>
</ann26>
<ann26>
<Code>115</Code>
<Omschrijving>Paritair Comité voor het glasbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>116</Code>
<Omschrijving>Paritair Comité voor de scheikundige nijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>117</Code>
<Omschrijving>Paritair Comité voor de petroleumnijverheid en -handel</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>118</Code>
<Omschrijving>Paritair Comité voor de voedingsnijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>119</Code>
<Omschrijving>Paritair Comité voor de handel in voedingswaren</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>120</Code>
<Omschrijving>Paritair Comité voor de textielnijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>120.01</Code>
<Omschrijving>Paritair Subcomité voor de textielnijverheid uit het administratief arrondissement Verviers</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>120.02</Code>
<Omschrijving>Paritair Subcomité voor de vlasbereiding</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann26>
<ann26>
<Code>120.03</Code>
<Omschrijving>Paritair Subcomité voor het vervaardigen van en de handel in zakken in jute of in vervangingsmaterialen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>121</Code>
<Omschrijving>Paritair Comité voor de schoonmaak</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>124</Code>
<Omschrijving>Paritair Comité voor het bouwbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>125</Code>
<Omschrijving>Paritair Comité voor de houtnijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>125.01</Code>
<Omschrijving>Paritair Subcomité voor de bosontginningen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>125.02</Code>
<Omschrijving>Paritair Subcomité voor de zagerijen en aanverwante nijverheden</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>125.03</Code>
<Omschrijving>Paritair Subcomité voor de houthandel</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>126</Code>
<Omschrijving>Paritair Comité voor de stoffering en de houtbewerking</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>127</Code>
<Omschrijving>Paritair Comité voor de handel in brandstoffen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>127.02</Code>
<Omschrijving>Paritair Subcomité voor de handel in brandstoffen van Oost-Vlaanderen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2016</einde_geldigheid>
</ann26>
<ann26>
<Code>128</Code>
<Omschrijving>Paritair Comité voor het huiden- en lederbedrijf en vervangingsproducten</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>128.01</Code>
<Omschrijving>Paritair Subcomité voor de leerlooierij en de handel in ruwe huiden en vellen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2018</einde_geldigheid>
</ann26>
<ann26>
<Code>128.02</Code>
<Omschrijving>Paritair Subcomité voor de schoeiselindustrie, de laarzenmakers en de maatwerkers</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2018</einde_geldigheid>
</ann26>
<ann26>
<Code>128.03</Code>
<Omschrijving>Paritair Subcomité voor het marokijnwerk en de handschoennijverheid</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2018</einde_geldigheid>
</ann26>
<ann26>
<Code>128.05</Code>
<Omschrijving>Paritair Subcomité voor de zadelmakerij, de vervaardiging van riemen en industriële artikelen in leder</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2018</einde_geldigheid>
</ann26>
<ann26>
<Code>128.06</Code>
<Omschrijving>Paritair Subcomité voor de orthopedische schoeisels</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2014</einde_geldigheid>
</ann26>
<ann26>
<Code>129</Code>
<Omschrijving>Paritair Comité voor de voortbrenging van papierpap, papier en karton</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>130</Code>
<Omschrijving>Paritair Comité voor het drukkerij-, grafische kunst- en dagbladbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>132</Code>
<Omschrijving>Paritair Comité voor de ondernemingen van technische land- en tuinbouwwerken</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>133</Code>
<Omschrijving>Paritair Comité voor het tabaksbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>136</Code>
<Omschrijving>Paritair Comité voor de papier- en kartonbewerking</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>139</Code>
<Omschrijving>Paritair Comité voor de binnenscheepvaart</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>139.01</Code>
<Omschrijving>Paritair Subcomité voor de sleep-diensten</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann26>
<ann26>
<Code>140</Code>
<Omschrijving>Paritair Comité voor het vervoer en de logistiek</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>140.01</Code>
<Omschrijving>Paritair Subcomité voor de autobussen en autocars</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>140.02</Code>
<Omschrijving>Paritair Subcomité voor de taxi's</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>140.03</Code>
<Omschrijving>Paritair Subcomité voor het wegvervoer en de logistiek voor rekening van derden</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>140.04</Code>
<Omschrijving>Paritair Subcomité voor de grondafhandeling op luchthavens</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/04/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>140.05</Code>
<Omschrijving>Paritair Subcomité voor de verhuizing</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/10/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>142</Code>
<Omschrijving>Paritair Comité voor de ondernemingen waar teruggewonnen grondstoffen opnieuw ter waarde worden gebracht</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>142.01</Code>
<Omschrijving>Paritair Subcomité voor de terugwinning van metalen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>142.02</Code>
<Omschrijving>Paritair Subcomité voor de terugwinning van lompen</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>142.03</Code>
<Omschrijving>Paritair Subcomité voor de terugwinning van papier</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>142.04</Code>
<Omschrijving>Paritair Subcomité voor de terugwinning van allerlei producten</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>143</Code>
<Omschrijving>Paritair Comité voor de zeevisserij</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>144</Code>
<Omschrijving>Paritair Comité voor de landbouw</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>145</Code>
<Omschrijving>Paritair Comité voor het tuinbouwbedrijf</Omschrijving>
<CategorieNL>Paritaire organen bevoegd voor de werknemers die hoofdzakelijk handarbeid verrichten en hun werkgevers</CategorieNL>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann26>
<ann26>
<Code>146</Code>
<Omschrijving>Paritair Comité voor het bosbouwbedrijf</Omschrijving>