<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT employee-code (type?, code?, description?
	      , employee-type?, presence?, begin-validity?, end-validity?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (employee-code+)>
     <!ELEMENT type (#PCDATA)>
     <!ELEMENT code (#PCDATA)>
     <!ELEMENT description (#PCDATA)>
     <!ELEMENT employee-type (#PCDATA)>
     <!ELEMENT presence (#PCDATA)>
     <!ELEMENT begin-validity (#PCDATA)>
     <!ELEMENT end-validity (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<employee-codes>
    <werknemers-kengetal>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>802</code>
        <description>Bijdrage in het kader van sociale toelage II voor de lokale politie</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2022/1</begin-validity>
        <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>805</code>
        <description>Responsabiliseringsbijdrage IGU - Inkomensgarantie-uitkering</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2020/2</begin-validity>
        <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>806</code>
        <description>Solidariteitsbijdrage op de vergoedingen voor zeegewenningsreizen</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2018/4</begin-validity>
        <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>817</code>
        <description>Egalisatiebijdrage verschuldigd voor bepaalde statutaire werknemers en de lokale mandatarissen</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2015/1</begin-validity>
        <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>851</code>
        <description>Bijzondere bijdrage op stortingen van werkgevers voor de vorming van een buitenwettelijk pensioen ten bate van hun personeelsleden of hun rechthebbenden</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2003/1</begin-validity>
        <end-validity>2011/3</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>861</code>
    <description>Bijdrage verschuldigd op de winstparticipaties</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>862</code>
    <description>Solidariteitsbijdrage op het gebruik van een bedrijfsvoertuig</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2005/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/2005</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>864</code>
    <description>Bijzondere bijdrage op stortingen van werkgevers voor de vorming van een buitenwettelijk pensioen; rechtstreekse stortingen aan ex-werknemers.</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2011/4</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/10/2011</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>865</code>
    <description>Bijzondere bijdrage op stortingen van werkgevers voor de vorming van een buitenwettelijk pensioen; stortingen in het kader van een ondernemingsplan</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2011/4</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/10/2011</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>866</code>
    <description>Bijzondere bijdrage op stortingen van werkgevers voor de vorming van een buitenwettelijk pensioen; stortingen in het kader van een sectorplan</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2011/4</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/10/2011</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
        <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
        <code>867</code>
        <description>Bijzondere aanvullende bijdrage op stortingen van werkgevers voor de vorming van een buitenwettelijk pensioen die een vastgesteld bedrag overschrijden</description>
        <employee-type>Andere (type werknemers)</employee-type>
        <presence>4</presence>
        <begin-validity>2012/4</begin-validity>
        <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>870</code>
    <description>Bijdrage verschuldigd op het dubbel vakantiegeld van de bedienden en, bij de provinciale en lokale besturen, de contractuelen en statutaire stagiairs met de vakantieregeling van de privésector, op de Copernicuspremie van de contractuelen in de federale overheidssector en bij de lokale politie en op de herstructureringspremie van de contractuele militairen</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijdrage niet gebonden aan een natuurlijke persoon</type>
    <code>875</code>
    <description>Bijdrage verschuldigd op het vakantiegeld toegekend door een provinciaal of lokaal bestuur aan contractuelen met de vakantieregeling van de openbare sector en aan vastbenoemden waarvan het pensioen niet ten laste is van de Staatskas en niet afhangt van de Pool der Parastatalen</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>4</presence>
    <begin-validity>2022/1</begin-validity>
    <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijdrage statutair personeelslid uitsluitend onderworpen aan overheidspensioenbijdrage</type>
    <code>676</code>
    <description>Statutaire werknemers met standplaats in het buitenland</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2015/1</begin-validity>
    <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijdrage statutair personeelslid uitsluitend onderworpen aan overheidspensioenbijdrage</type>
    <code>690</code>
    <description>Vastbenoemde geneesheren vrijgesteld van socialezekerheidsbijdragen op basis van art. 1, § 3 van de wet van 27.06.1969 en die op basis van art. 158 van de ziekenhuiswet van 10-7-2008 recht hebben op een overheidspensioen</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2022/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/2022</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>280</code>
    <description>Bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) na ontslag - aanvang SWAV vóór 01/04/2010 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>281</code>
    <description>Bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) na ontslag - aanvang SWAV tussen 01/04/2010 en 31/03/2012 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>282</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) na ontslag non-profitsector - aanvang SWAV tussen 01/04/2010 en 31/03/2012 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>283</code>
    <description>Bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) na ontslag - aanvang SWAV vanaf 01/04/2012 (uitz.: gevallen gelijkgesteld aan kgt 280 of 281)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2012/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2012</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>284</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) na ontslag in de non-profitsector - aanvang SWAV vanaf 01/04/2012 (uitz.: gevallen gelijkgesteld aan kgt 282)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2012/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2012</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>290</code>
    <description>Bijzondere werkgeversbijdrage werknemers in het stelsel van werkloosheid met aanvullende vergoeding bij oudere werknemers (SWAV) in tijdskrediet</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>883</code>
    <description>Ontslagen werknemers waarvoor er een bijdrage verschuldigd is op de aanvullende vergoedingen</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>3</presence>
    <begin-validity>2006/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2006</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage aanvullende vergoedingen</type>
    <code>885</code>
    <description>Werknemers met loopbaanonderbreking waarvoor er een bijdrage verschuldigd is op de aanvullende vergoedingen</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>3</presence>
    <begin-validity>2006/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2006</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage ontslagen statutaire werknemer</type>
    <code>876</code>
    <description>Bijdrage verschuldigd voor het ontslagen statutair personeel van de openbare sector en daarmee gelijkgestelden, wiens werkrelatie wordt beëindigd en militairen  teruggekeerd  naar het burgerleven aan te geven met de categorie 134 - Stelsel van de Ziekte- en Invaliditeitsverzekering</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage ontslagen statutaire werknemer</type>
    <code>877</code>
    <description>Bijdrage verschuldigd voor het ontslagen statutair personeel van de openbare sector en daarmee gelijkgestelden, wiens werkrelatie wordt beëindigd en militairen teruggekeerd naar het burgerleven aan te geven met de categorie 134 - Werkloosheidsstelsel</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage voor studenten</type>
    <code>840</code>
    <description>Solidariteitsbijdrage verschuldigd voor studenten-arbeiders in het kader van een overeenkomst voor studenten</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage voor studenten</type>
    <code>841</code>
    <description>Solidariteitsbijdrage verschuldigd voor studenten-bedienden in het kader van een overeenkomst voor studenten</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2004/3</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/07/2004</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>270</code>
    <description>Bijzondere werkgeversbijdrage voor een werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT) - aanvang SWT vóór 01/04/2010 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>271</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor een werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT) uit de non-profitsector - aanvang SWT vóór 01/04/2012 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>272</code>
    <description>Compenserende werkgeversbijdrage voor een werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>2015/3</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>30/09/2015</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>273</code>
    <description>Bijzondere werkgeversbijdrage voor een  werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT) - aanvang SWT tussen 01/04/2010 en 31/03/2012 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>274</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor een werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT) tijdens een periode van erkenning als onderneming in moeilijkheden of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>275</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor een werknemer in het stelsel van werkloosheid met bedrijfstoeslag (SWT) tijdens een periode van erkenning als onderneming in herstructurering - aanvang SWT tussen 01/04/2010 en 31/03/2012 of gelijkgesteld</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2010/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2010</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>276</code>
    <description>Bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met bedrijfstoeslag (SWT) - aanvang SWT vanaf 01/04/2012 (uitz.: gevallen gelijkgesteld aan kgt 270 of 273)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2012/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2012</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>277</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met bedrijfstoeslag (SWT) uit de non-profitsector - aanvang SWT vanaf 01/04/2012 (uitz.: gevallen gelijkgesteld aan kgt 271)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2012/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2012</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>278</code>
    <description>Verminderde bijzondere werkgeversbijdrage voor werknemers in het stelsel van werkloosheid met bedrijfstoeslag (SWT) tijdens een periode van erkenning als onderneming in herstructurering - aanvang SWT vanaf 01/04/2012 (uitz.: gevallen gelijkgesteld aan kgt 275)</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>2</presence>
    <begin-validity>2012/2</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/04/2012</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Bijzondere bijdrage werkloze met bedrijfstoeslag (SWT)</type>
    <code>879</code>
    <description>Werknemers in het stelsel van werkloosheid met bedrijfstoeslag (SWT) waarvoor een bijzondere bijdrage verschuldigd is</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>1</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>010</code>
    <description>Gepensioneerde werknemers die worden bedoeld in artikel 42 bis van de arbeidsongevallenwet van 10.04.1971 en in artikel 66 van de wetten betreffende de preventie van beroepsziekten en de vergoeding van de schade die uit die ziekten voortvloeit, gecoördineerd op 03.06.1970 of als het slachtoffer de leeftijd van 65 jaar bereikt heeft.</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>3</presence>
    <begin-validity>2015/4</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/10/2015</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>013</code>
    <description>Kansarme jongeren</description>
    <employee-type>Speciale handarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>014</code>
    <description>Zeevarenden in de koopvaardij-, bagger- of zeesleepvaartsector</description>
    <employee-type>Zeevarenden</employee-type>
    <presence>3</presence>
    <begin-validity>2018/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/2018</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>015</code>
    <description>Werklieden en gelijkgestelden, inbegrepen huispersoneel</description>
    <employee-type>Gewone handarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>016</code>
    <description>Mijnwerkers</description>
    <employee-type>Mijnwerkers (handarbeiders)</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>027</code>
    <description>Leerplichtige werklieden en stagiairs</description>
    <employee-type>Leerplichtige gewone handarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>041</code>
    <description>Dienstboden die het slachtoffer zijn van een arbeidsongeval, gebeurd vóór 01/04/1983</description>
    <employee-type>Dienstboden (handarbeiders)</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>045</code>
    <description>Dienstboden die het slachtoffer zijn van een arbeidsongeval, gebeurd sinds 01/04/1983 of die het slachtoffer zijn van een beroepsziekte</description>
    <employee-type>Dienstboden (handarbeiders)</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>487</code>
    <description>Leerplichtige hoofdarbeiders en stagiairs</description>
    <employee-type>Leerplichtige hoofdarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>493</code>
    <description>Geneesheren in opleiding tot geneesheer-specialist. Kansarme jongeren. Bursalen van een land buiten de Europese Economische Ruimte.</description>
    <employee-type>Speciale hoofdarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>494</code>
    <description>Betaalde sportbeoefenaars, behalve beroepswielrenners (in het bezit van een licentie van de BWB) die een arbeidsongeval opgelopen hebben sinds 01/01/1985</description>
    <employee-type>Speciale hoofdarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>495</code>
    <description>Hoofdarbeiders en gelijkgestelden, huisbedienden, alsook beroepswielrenners (in het bezit van een licentie van de BWB) die een arbeidsongeval opgelopen hebben sinds 01/01/1985, erkende onthaalouders, kunstenaars, gelegenheidswerknemers in de horeca.</description>
    <employee-type>Gewone hoofdarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Fedris bijdrage</type>
    <code>675</code>
    <description>Statutaire werknemers</description>
    <employee-type>Andere (type werknemers)</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Gewone bijdrage</type>
    <code>010</code>
    <description>Tijdelijke werklieden in de tuinbouw en  in de landbouw  (werkgevers met werkgeverscategorieën 194, 494, 594, 193, 293, 097 en 497) en tot en met het tweede kwartaal 2007 werklieden - gelegenheidswerknemer in de horeca (werkgevers met werkgeverscategorieën 016, 017, 097 en 497).</description>
    <employee-type>Seizoenhandarbeiders</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>
    <end-validity>9999/4</end-validity>
    <begin_geldigheid>01/01/1900</begin_geldigheid>
    <einde_geldigheid>01/01/9999</einde_geldigheid>
    </employee-code>
    <employee-code>
    <type>Gewone bijdrage</type>
    <code>011</code>
    <description>Werklieden van de speciale categorie aan te geven met forfaitaire lonen door werkgevers met werkgeverscategorieën 016, 017, 019, 116, 117, 216, 217 en, vanaf het eerste kwartaal 2010, 066, 323, 562 et 662 en, tot en met het eerste kwartaal 2007, 020, 023, 068, 146, 158, 166, 323 en 562 (loonmatigingsbijdrage niet verschuldigd) en leerlingen van deze categorie vanaf het jaar waarin ze 19 jaar worden. Vanaf het vierde kwartaal 2013 ook werklieden van de speciale categorie aan te geven met forfaitaire lonen door werkgevers met werkgeverscategorieën 317, 097 en 497.</description>
    <employee-type>Handarbeiders tegen forfait</employee-type>
    <presence>3</presence>
    <begin-validity>2003/1</begin-validity>