<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann39 (Code?, Omschrijving?, Geldig_vanaf?, Geldig_tot?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann39+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT Geldig_vanaf (#PCDATA)>
     <!ELEMENT Geldig_tot (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann39>
<Code>10</Code>
<Omschrijving>Werkgever</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>11</Code>
<Omschrijving>Sociaal Secretariaat</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>12</Code>
<Omschrijving>Dienstverlener</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>13</Code>
<Omschrijving>Curator</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>20</Code>
<Omschrijving>Inspecteur RSZ hoedanigheid werkgever</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>22</Code>
<Omschrijving>Systeem</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>23</Code>
<Omschrijving>Inspecteur RSZ hoedanigheid RSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>24</Code>
<Omschrijving>Agent hoedanigheid RSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>30</Code>
<Omschrijving>Inspecteur MET</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>31</Code>
<Omschrijving>Inspecteur MSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>50</Code>
<Omschrijving>Agent MET</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>51</Code>
<Omschrijving>Agent MSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>52</Code>
<Omschrijving>Agent NIC</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>53</Code>
<Omschrijving>Agent A O</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>54</Code>
<Omschrijving>Agent FBZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>55</Code>
<Omschrijving>Agent RIZIV</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>56</Code>
<Omschrijving>Agent RVP</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>57</Code>
<Omschrijving>Agent RJV</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>58</Code>
<Omschrijving>Agent FOD Financën Thesaurie</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>59</Code>
<Omschrijving>Agent Fondsen Best. Zekerheid</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>60</Code>
<Omschrijving>Agent RVA</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>61</Code>
<Omschrijving>Agent RSVZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>62</Code>
<Omschrijving>Agent HVZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>63</Code>
<Omschrijving>Agent DOSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>2014/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2014</einde_geldigheid>
</ann39>
<ann39>
<Code>64</Code>
<Omschrijving>Agent Admin. Pensioenen</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>65</Code>
<Omschrijving>Agent KSZ</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>66</Code>
<Omschrijving>Agent HVW</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>67</Code>
<Omschrijving>Agent HZIV</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>68</Code>
<Omschrijving>Agent RKW</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>74</Code>
<Omschrijving>Agent IVA Jongerenwelzijn</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>90</Code>
<Omschrijving>Werkgever PPL</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>91</Code>
<Omschrijving>Dienstverrichter PPL</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>92</Code>
<Omschrijving>Dienstverlener RSZ PPO</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>2014/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2014</einde_geldigheid>
</ann39>
<ann39>
<Code>93</Code>
<Omschrijving>Inspecteur RSZ (ex-DIBISS)</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
<ann39>
<Code>94</Code>
<Omschrijving>Agent RSZ (ex-DIBISS)</Omschrijving>
<Geldig_vanaf>1900/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann39>
</List>
