<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann41 (Code?, DescFr?, Geldig_vanaf?, Geldig_tot?)>
     <!ELEMENT List (ann41+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT DescFr (#PCDATA)>
     <!ELEMENT Geldig_vanaf (#PCDATA)>
     <!ELEMENT Geldig_tot (#PCDATA)>
]>
<List>
<ann41>
<Code>051</Code>
<DescFr>Intérêts arrêtés à la date de clôture du présent document et calculés sur le solde en cotisations du trimestre concerné.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>101</Code>
<DescFr>Cotisations déclarées pour le trimestre concerné.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>104</Code>
<DescFr>Cotisations dues en application de l'arrêté royal du 18/06/1976.</DescFr>
<Geldig_vanaf>1972/2</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>112</Code>
<DescFr>Cotisation annuelle de vacances (cotisation calculée sur base des salaires ouvriers déclarés pour l'année précédant celle renseignée).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>121</Code>
<DescFr>Rectification en faveur de l'O.N.S.S. apportée aux cotisations déclarées.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>2004/4</Geldig_tot>
</ann41>
<ann41>
<Code>121</Code>
<DescFr>Rectification en faveur de l'O.N.S.S. apportée aux cotisations déclarées (à l'exclusion des cotisations de solidarité "véhicule de société").</DescFr>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>128</Code>
<DescFr>Rectification en faveur de l'O.N.S.S. apportée à la cotisation de solidarité « véhicule de société ».</DescFr>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>132</Code>
<DescFr>Rectification en faveur de l'O.N.S.S. apportée à la cotisation annuelle de vacances (cotisation calculée sur base des salaires ouvriers déclarés pour l'année précédant celle renseignée).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>135</Code>
<DescFr>Rectification en faveur de l'O.N.S.S. de la réduction des cotisations pour travailleurs manuels (Maribel).</DescFr>
<Geldig_vanaf>1983/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>201</Code>
<DescFr>Paiement de cotisations.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>204</Code>
<DescFr>Montant en faveur de l'employeur en application de l'arrêté royal du 18/06/1976.</DescFr>
<Geldig_vanaf>1972/2</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>221</Code>
<DescFr>Rectification en faveur de l'employeur apportée aux cotisations déclarées.</DescFr>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>2004/4</Geldig_tot>
</ann41>
<ann41>
<Code>221</Code>
<DescFr>Rectification en faveur de l'employeur apportée aux cotisations déclarées (à l'exclusion des cotisations de solidarité "véhicule de société").</DescFr>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>228</Code>
<DescFr>Rectification en faveur de l'employeur apportée à la cotisation de solidarité « véhicule de société »).</DescFr>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>232</Code>
<DescFr>Rectification en faveur de l'employeur apportée à la cotisation annuelle de vacances (cotisation calculée sur base des salaires ouvriers déclarés pour l'année précédant celle renseignée).</DescFr>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>261</Code>
<DescFr>Paiement de cotisations résultant d'une retenue de 35 % effectuée par un entrepreneur principal (Art. 30bis de la loi du 27/06/1969).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>301</Code>
<DescFr>Majoration appliquée en raison du non paiement de la cotisation dans le délai fixé par la loi égal à 10 % du montant restant impayé à la date d'échéance du trimestre concerné (Article 54 de l'arrêté royal du 28/11/1969).</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>306</Code>
<DescFr>Indemnité forfaitaire pour défaut de remise de la déclaration dans le délai prévu à l'article 33, § 2 ou à l'article 35bis de l'arrêté royal du 28/11/1969 (article 54ter, § 2, alinéa 1 de l'arrêté royal du 28/11/1969).</DescFr>
<Geldig_vanaf>1963/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>311</Code>
<DescFr>Indemnité forfaitaire pour non paiement ou paiement insuffisant des provisions mensuelles dans les délais fixés (article 54bis de l'arrêté royal du 28/11/1969).</DescFr>
<Geldig_vanaf>2001/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>316</Code>
<DescFr>Indemnité forfaitaire pour absence de déclaration ou déclaration incomplète ou inexacte, de 50 EURO entés de 4 EURO  par ligne d'occupation manquante ou pour laquelle la rémunération à prendre en compte est modifiée (article 54ter, § 1er de l'arrêté royal du 28/11/1969).</DescFr>
<Geldig_vanaf>2006/2</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>326</Code>
<DescFr>Indemnité forfaitaire pour transmission habituelle d'une déclaration incomplète ou inexacte (article 54ter, § 2, alinéa 3 de l'arrêté royal du 28/11/1969).</DescFr>
<Geldig_vanaf>2006/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>356</Code>
<DescFr>Indemnité forfaitaire égale au double de la cotisation de solidarité « véhicule de société » (article 38, § 3quater de la loi du 29/06/1981, tel que remplacé par la loi du 20/07/2006).</DescFr>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>401</Code>
<DescFr>Paiement de la majoration et/ou des indemnités forfaitaires.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>422</Code>
<DescFr>Réduction de majoration.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>429</Code>
<DescFr>Réduction de l'indemnité forfaitaire pour rentrée tardive de la déclaration.</DescFr>
<Geldig_vanaf>1993/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>432</Code>
<DescFr>Réduction de l'indemnité forfaitaire pour non paiement ou paiement insuffisant des provisions mensuelles.</DescFr>
<Geldig_vanaf>2001/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>439</Code>
<DescFr>Réduction de l'indemnité forfaitaire pour absence de déclaration ou déclaration incomplète ou inexacte.</DescFr>
<Geldig_vanaf>2006/2</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>449</Code>
<DescFr>Réduction de l'indemnité forfaitaire pour transmission habituelle d'une déclaration incomplète ou inexacte.</DescFr>
<Geldig_vanaf>2006/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>461</Code>
<DescFr>Paiement de majorations, résultant d'une retenue de 35% effectuée par un entrepreneur principal (Art. 30bis de la loi du 27/06/1969).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>601</Code>
<DescFr>Paiement d'intérêts.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>622</Code>
<DescFr>Réduction d'intérêts.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>661</Code>
<DescFr>Paiement d'intérêts, résultant d'une retenue de 35 % effectuée par un entrepreneur principal (Art. 30bis de la loi du 27/06/1969).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>901</Code>
<DescFr>"Déclaration ""néant"", pas de cotisations déclarées."</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>921</Code>
<DescFr>Cotisations déclarées compte tenu des rectifications en faveur de l'employeur apportées à la déclaration originale.</DescFr>
<Geldig_vanaf>1963/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
<ann41>
<Code>932</Code>
<DescFr>Cotisation annuelle de vacances (compte tenu des rectifications en faveur de l'employeur apportées au montant de l'avis de débit original).</DescFr>
<Geldig_vanaf>1964/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
</ann41>
</List>
