<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann32 (categoryfr?, CodePPL?, Code?, Description?, Vanaf?, Tot?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann32+)>
     <!ELEMENT categoryfr (#PCDATA)>
     <!ELEMENT CodePPL (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT Vanaf (#PCDATA)>
     <!ELEMENT Tot (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann32>
<categoryfr>Déclaration Risque Social - salaire exact</categoryfr>
<CodePPL>21</CodePPL>
<Code>21</Code>
<Description>Avantages non soumis aux cotisations ONSS ordinaires</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Déclaration Risque Social - salaire exact</categoryfr>
<CodePPL>30</CodePPL>
<Code>30</Code>
<Description>Salaire garanti deuxième semaine</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Déclaration Risque Social - salaire exact</categoryfr>
<CodePPL>31</CodePPL>
<Code>31</Code>
<Description>Indemnité CCT 12bis/13bis</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Déclaration Risque Social - salaire exact</categoryfr>
<CodePPL>32</CodePPL>
<Code>32</Code>
<Description>Rémunération nette programme d'activation</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Déclaration Risque Social - salaire exact</categoryfr>
<CodePPL>33</CodePPL>
<Code>33</Code>
<Description>Rémunération brute pour un travailleur à temps partiel bénéficiant d'une allocation de garantie de revenus</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>29</CodePPL>
<Code>29</Code>
<Description>Solde du budget mobilité versé en espèces et qui correspond au 3ème pilier</Description>
<Vanaf>2019/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2019</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>770</CodePPL>
<Code>10</Code>
<Description>Avantage de toute nature sur l'utilisation personnelle d'un véhicule de société ou, jusqu'au 31/12/2020, sur l'allocation de mobilité contre restitution d'un véhicule de société ou sur le véhicule de société respectueux de l'environnement dans le cadre du budget de mobilité</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>780</CodePPL>
<Code>20</Code>
<Description>Participations aux bénéfices</Description>
<Vanaf>2010/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>790</CodePPL>
<Code>20</Code>
<Description>Versements d'employeurs pour la constitution d'une pension extralégale au profit des membres de leur personnel ou de leurs ayants-droit</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2011/3</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2011</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>791</CodePPL>
<Code>20</Code>
<Description>Amendes de circulation remboursées par l'employeur</Description>
<Vanaf>2009/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2009</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>792</CodePPL>
<Code>20</Code>
<Description>Versements directs d'une pension extra-légale au profit des travailleurs qui sortent de service (en raison de mise à la retraite)</Description>
<Vanaf>2011/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2011</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>793</CodePPL>
<Code>20</Code>
<Description>Versements effectués par les employeurs pour la constitution d'une pension extra-légale dans le cadre d'un plan d'entreprise</Description>
<Vanaf>2011/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2011</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>794</CodePPL>
<Code>20</Code>
<Description>Tranche de rémunération inférieure ou égale au montant plafond pour versements des employeurs en vue de la constitution d'une pension extra-légale - Anvers</Description>
<Vanaf>2010/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>795</CodePPL>
<Code>20</Code>
<Description>Tranche de rémunération supérieure au montant plafond pour versements des employeurs en vue de la constitution d'une pension extra-légale - Anvers</Description>
<Vanaf>2010/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2010</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>796</CodePPL>
<Code>20</Code>
<Description>Rémunération pour versements des employeurs en vue de la constitution d'une pension extra-légale - de 0 à 9 ans d'ancienneté - Bruges</Description>
<Vanaf>2013/1</Vanaf>
<Tot>2019/4</Tot>
<begin_geldigheid>01/01/2013</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>797</CodePPL>
<Code>20</Code>
<Description>Rémunération pour versements des employeurs en vue de la constitution d'une pension extra-légale - de 10 à 19 ans d'ancienneté - Bruges</Description>
<Vanaf>2013/1</Vanaf>
<Tot>2019/4</Tot>
<begin_geldigheid>01/01/2013</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>798</CodePPL>
<Code>20</Code>
<Description>Rémunération pour versements des employeurs en vue de la constitution d'une pension extra-légale - de 20 à 29 ans d'ancienneté - Bruges</Description>
<Vanaf>2013/1</Vanaf>
<Tot>2019/4</Tot>
<begin_geldigheid>01/01/2013</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités assujetties à une cotisation spéciale</categoryfr>
<CodePPL>799</CodePPL>
<Code>20</Code>
<Description>Rémunération pour versements des employeurs en vue de la constitution d'une pension extra-légale - de 30 ans d'ancienneté à plus - Bruges</Description>
<Vanaf>2013/1</Vanaf>
<Tot>2019/4</Tot>
<begin_geldigheid>01/01/2013</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités pour rupture unilatérale de la relation de travail</categoryfr>
<CodePPL>130</CodePPL>
<Code>3</Code>
<Description>Indemnité pour rupture unilatérale de la relation de travail - exprimé en temps de travail (concerne le personnel non nommé)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités pour rupture unilatérale de la relation de travail</categoryfr>
<CodePPL>131</CodePPL>
<Code>4</Code>
<Description>Indemnité pour rupture unilatérale de la relation de travail - pas exprimé en temps de travail</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités pour rupture unilatérale de la relation de travail</categoryfr>
<CodePPL>132</CodePPL>
<Code>9</Code>
<Description>Indemnité pour rupture unilatérale de la relation de travail - exprimé en temps de travail (concerne le personnel nommé)</Description>
<Vanaf>2005/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2005</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>26</CodePPL>
<Code>26</Code>
<Description>Primes et/ou subsides autres que Maribel social perçus par l'employeur</Description>
<Vanaf>2018/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2018</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>401</CodePPL>
<Code>20</Code>
<Description>Allocation horaire pour des prestations de service supplémentaires non récupérable - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>403</CodePPL>
<Code>20</Code>
<Description>Cadeaux en nature, en espèces ou en chèques sous les conditions de l'art.19, §2, 14° AR 28-11-1969, et réduction du prix des produits ou services sous les conditions de l'art. 19, §2, 19° de l'AR du 28-11-1969</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>404</CodePPL>
<Code>20</Code>
<Description>Avantages en nature ou sous la forme de chèques - lien avec prestations fournies du trimestre - exonérés</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>406</CodePPL>
<Code>20</Code>
<Description>Avantages en nature ou sous la forme de chèques - sans lien avec les prestations du trimestre - exonérés</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>408</CodePPL>
<Code>20</Code>
<Description>Montant de la part de l'employeur dans les chèques repas sous les conditions de l'article 19bis, §2 de l'AR du 28-11-1969</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2018/3</Tot>
<begin_geldigheid>01/07/2004</begin_geldigheid>
<einde_geldigheid>30/09/2018</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>408</CodePPL>
<Code>24</Code>
<Description>Montant de la part de l'employeur dans les chèques repas sous les conditions de l'article 19bis, §2 de l'AR du 28-11-1969</Description>
<Vanaf>2018/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2018</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>409</CodePPL>
<Code>20</Code>
<Description>Montant de la part du travailleur dans les chèques repas sous les conditions de l'article 19bis, §2 de l'AR du 28-11-1969</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>417</CodePPL>
<Code>20</Code>
<Description>Prime de fin d'année - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>421</CodePPL>
<Code>20</Code>
<Description>Allocation de foyer / résidence - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>422</CodePPL>
<Code>20</Code>
<Description>Allocation de diplôme - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>423</CodePPL>
<Code>20</Code>
<Description>Indemnité pour connaissance 2e langue - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>424</CodePPL>
<Code>20</Code>
<Description>Allocation pour fonctions supérieures - exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>433</CodePPL>
<Code>20</Code>
<Description>Autres allocations et primes - Pas de lien avec les prestations du trimestre - exonérées</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>434</CodePPL>
<Code>20</Code>
<Description>Autres allocations et primes - liées aux prestations du trimestre - exonérées</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>435</CodePPL>
<Code>20</Code>
<Description>Allocation pour prestations de nuit - exonérée de cotisations de sécurité sociale - pas de cotisations de pension</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>436</CodePPL>
<Code>20</Code>
<Description>Allocation pour prestations de week-end et jours fériés - exonérée de cotisations de sécurité sociale - pas de cotisations de pension</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>437</CodePPL>
<Code>20</Code>
<Description>Indemnité de garde -   exonérée</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>440</CodePPL>
<Code>20</Code>
<Description>Indemnités pour le travailleur lorsque l'employeur ne respecte pas ses obligations légales, contractuelles ou statutaires (par exemple indemnité de licenciement pour travailleur protégé)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>441</CodePPL>
<Code>20</Code>
<Description>Indemnité de vêtements, logement, frais de déplacement et de séjour (par exemple frais de l'employeur = remboursement du prix ou mise à disposition de vêtements de travail, équipement ou transport)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2018/3</Tot>
<begin_geldigheid>01/07/2004</begin_geldigheid>
<einde_geldigheid>30/09/2018</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>441</CodePPL>
<Code>24</Code>
<Description>Indemnité de vêtements, logement, frais de déplacement et de séjour (par exemple frais de l'employeur = remboursement du prix ou mise à disposition de vêtements de travail, équipement ou transport)</Description>
<Vanaf>2018/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2018</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>442</CodePPL>
<Code>20</Code>
<Description>Frais de déplacement de et vers le lieu de travail</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2018/3</Tot>
<begin_geldigheid>01/07/2004</begin_geldigheid>
<einde_geldigheid>30/09/2018</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>442</CodePPL>
<Code>24</Code>
<Description>Frais de déplacement de et vers le lieu de travail</Description>
<Vanaf>2018/4</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/10/2018</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>443</CodePPL>
<Code>20</Code>
<Description>Montant octroyé en raison d'une affiliation à une organisation syndicale reconnue</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>444</CodePPL>
<Code>20</Code>
<Description>Supplément à un avantage de sécurité sociale pour une autre raison qu'une indemnité suite à une maladie ou un accident (ex: prime d'encouragement interruption de carrière, prime d'assurance hospitalisation)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>452</CodePPL>
<Code>20</Code>
<Description>Prime accordée au travailleur soit dans le cadre du travail à mi-temps à partir de l'âge de 55 ou 50 ans, soit dans le cadre de la fin de carrière en douceur</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>454</CodePPL>
<Code>20</Code>
<Description>Indemnité accordée aux ordonnateurs, gardes, conservateurs, fossoyeurs, brigadiers-fossoyeurs, porteurs aux services des sépultures, préposés aux dépôts mortuaire et à la morgue - exonérée de cotisations de sécurité sociale - cotisations de pension</Description>
<Vanaf>2005/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2005</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>490</CodePPL>
<Code>20</Code>
<Description>Rente pour incapacité de travail permanente (totale ou partielle) suite à un accident de travail ou une maladie professionnelle</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>801</CodePPL>
<Code>1</Code>
<Description>Allocation horaire pour des prestations de services supplémentaires non récupérables - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>804</CodePPL>
<Code>1</Code>
<Description>Avantages en nature ou sous la forme de chèques - lien avec prestations fournies du trimestre - soumis</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>806</CodePPL>
<Code>2</Code>
<Description>Avantages en nature ou sous la forme de chèques - sans lien avec les prestations du trimestre - soumis</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>817</CodePPL>
<Code>2</Code>
<Description>Prime de fin d'année - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>821</CodePPL>
<Code>1</Code>
<Description>Allocation de foyer / résidence - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>822</CodePPL>
<Code>1</Code>
<Description>Allocation de diplôme - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>823</CodePPL>
<Code>1</Code>
<Description>Indemnité pour connaissance 2e langue - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>824</CodePPL>
<Code>1</Code>
<Description>Allocation pour fonctions supérieures - soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>833</CodePPL>
<Code>2</Code>
<Description>Autres allocations et primes - pas de lien avec les prestations du trimestre - soumises</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>834</CodePPL>
<Code>1</Code>
<Description>Autres allocations et primes - liées aux prestations du trimestre - soumises</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>835</CodePPL>
<Code>1</Code>
<Description>Allocation pour prestations de nuit - soumise aux cotisations de sécurité sociale - pas de cotisations de pension</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>836</CodePPL>
<Code>1</Code>
<Description>Allocation pour prestations  de week-end et jours fériés - soumise aux cotisations de sécurité sociale - pas de cotisations de pension</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>837</CodePPL>
<Code>1</Code>
<Description>Indemnité de garde -  soumise</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>851</CodePPL>
<Code>5</Code>
<Description>Supplément de traitement accordé au travailleur qui a choisi la semaine volontaire de 4 jours - mesure transitoire (loi du 10/04/1995)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>852</CodePPL>
<Code>5</Code>
<Description>Supplément de traitement accordé au travailleur qui a choisi la semaine de 4 jours (loi du 19/07/2012)</Description>
<Vanaf>2012/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>853</CodePPL>
<Code>1</Code>
<Description>Prime accordée au  personnel infirmier, soignant et assimilé dans le cadre de l'aménagement de fin de carrière (AR du 23-09-2002)</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>854</CodePPL>
<Code>1</Code>
<Description>Indemnité accordée aux ordonnateurs, gardes, conservateurs, fossoyeurs, brigadiers-fossoyeurs, porteurs aux services des sépultures, préposés aux dépôts mortuaire et à la morgue - soumise aux cotisations de sécurité sociale - cotisations de pension</Description>
<Vanaf>2005/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2005</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>855</CodePPL>
<Code>1</Code>
<Description>Suppléments de traitement accordés en application des points 6.2 et 6.3 de la Charte sociale du 28.04.1994 de la Région de Bruxelles-Capitale - soumis aux cotisations de sécurité sociale - cotisations de pension</Description>
<Vanaf>2005/1</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/2005</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires de nature générale</categoryfr>
<CodePPL>940</CodePPL>
<Code>1</Code>
<Description>Indemnités pour prestations effectuées en tant que (ambulancier) volontaire n'ayant pas le statut de pompier dans le cadre du service 100</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2017/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2017</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires pour catégories spécifiques de personnel - médecins</categoryfr>
<CodePPL>524</CodePPL>
<Code>20</Code>
<Description>Quote-part variable dans le pool - exonérée de cotisations sociales conformément à l'article 30</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires pour catégories spécifiques de personnel - médecins</categoryfr>
<CodePPL>921</CodePPL>
<Code>1</Code>
<Description>Barème, traitement garanti et quote-part garantie dans le pool ou honoraires</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2010/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2010</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires pour catégories spécifiques de personnel - médecins</categoryfr>
<CodePPL>924</CodePPL>
<Code>1</Code>
<Description>Quote-part variable dans le pool - soumise aux cotisations sociales</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>
<categoryfr>Indemnités supplémentaires pour catégories spécifiques de personnel - personnel de police  (nouveau statut)</categoryfr>
<CodePPL>570</CodePPL>
<Code>20</Code>
<Description>(nouveau statut) Diverses allocations et indemnités - exonérées</Description>
<Vanaf>2004/3</Vanaf>
<Tot>2021/4</Tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/12/2021</einde_geldigheid>
</ann32>
<ann32>