=== BartVertongen/BelgianHR/schema/Dimona/IDFLUX_20223.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple elements -->
	<xs:element name="AttestationStatus">
		<xs:annotation>
			<xs:documentation>00110</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="1"/>
				<xs:enumeration value="0"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="CompanyID">
		<xs:annotation>
			<xs:documentation>00014</xs:documentation>
			<xs:appinfo source="ConversionID">CompanyID_conversion1</xs:appinfo>
			<xs:appinfo source="TDOType">xs:companyId</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="1999999943"/>
				<xs:totalDigits value="10"/>
				<xs:pattern value="0|\d{9}|\d{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="EffectiveStartingDate">
		<xs:annotation>
			<xs:documentation>00813</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="EmployerId" type="EmployerIdType">
		<xs:annotation>
			<xs:documentation>90256</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="Form">
		<xs:annotation>
			<xs:documentation>90059</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="FormType">
					<xs:sequence>
						<xs:element ref="Reference"/>
						<xs:element ref="IdfluxInformation"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="FormCreationDate">
		<xs:annotation>
			<xs:documentation>00218</xs:documentation>
			<xs:appinfo source="ConversionID">Date_conversion1</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="FormCreationHour">
		<xs:annotation>
			<xs:documentation>00299</xs:documentation>
			<xs:appinfo source="ConversionID">Time_conversion1</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:time">
				<xs:pattern value="\d{2}:\d{2}:\d{2}.\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Identification">
		<xs:annotation>
			<xs:documentation>00296</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="7"/>
				<xs:enumeration value="IDFLUX"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="IDFLUX">
		<xs:annotation>
			<xs:documentation>90323</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Form"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="IdfluxInformation">
		<xs:annotation>
			<xs:documentation>90328</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="IdfluxInformationType">
					<xs:sequence>
						<xs:element ref="EmployerId"/>
						<xs:element ref="ValidSituation"/>
						<xs:element ref="OutdatedSituation"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="INSS">
		<xs:annotation>
			<xs:documentation>00024</xs:documentation>
			<xs:appinfo source="ConversionID">Inss_conversion1</xs:appinfo>
			<xs:appinfo source="TDOType">xs:inss</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="11"/>
				<xs:pattern value="[0]|\d{11}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="JustificationCode">
		<xs:annotation>
			<xs:documentation>00536</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="2"/>
				<xs:pattern value="\d{2}"/>
				<xs:enumeration value="90"/>
				<xs:enumeration value="91"/>
				<xs:enumeration value="92"/>
				<xs:enumeration value="93"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="NOSSLPARegistrationNbr">
		<xs:annotation>
			<xs:documentation>00109</xs:documentation>
			<xs:appinfo source="ConversionID">NossAPL_conversion1</xs:appinfo>
			<xs:appinfo source="TDOType">xs:nossLpaRegistrationNbr</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="99999926"/>
				<xs:totalDigits value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="NOSSRegistrationNbr">
		<xs:annotation>
			<xs:documentation>00011</xs:documentation>
			<xs:appinfo source="ConversionID">Noss_conversion1</xs:appinfo>
			<xs:appinfo source="TDOType">xs:nossRegistrationNbr</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="100006"/>
				<xs:maxInclusive value="199999934"/>
				<xs:totalDigits value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="OutdatedSituation" type="OutdatedSituationType">
		<xs:annotation>
			<xs:documentation>90327</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="ProvisionalNSSONbr">
		<xs:annotation>
			<xs:documentation>00948</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="5000000120"/>
				<xs:maxInclusive value="5999999989"/>
				<xs:totalDigits value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Reference" type="ReferenceType">
		<xs:annotation>
			<xs:documentation>90082</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="ReferenceNbr">
		<xs:annotation>
			<xs:documentation>00222</xs:documentation>
			<xs:appinfo source="ConversionID">TicketNumber_conversion1</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="ReferenceOrigin">
		<xs:annotation>
			<xs:documentation>00298</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="1"/>
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="ReferenceType">
		<xs:annotation>
			<xs:documentation>00221</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="1"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="TypeForm">
		<xs:annotation>
			<xs:documentation>00297</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="2"/>
				<xs:enumeration value="SU"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="ValidSituation" type="ValidSituationType">
		<xs:annotation>
			<xs:documentation>90326</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="WorkerBirthdate">
		<xs:annotation>
			<xs:documentation>00028</xs:documentation>
			<xs:appinfo source="ConversionID">Date_conversion2</xs:appinfo>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="10"/>
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="WorkerFirstName">
		<xs:annotation>
			<xs:documentation>00026</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="24"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="WorkerName">
		<xs:annotation>
			<xs:documentation>00025</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="48"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="WorkerSex">
		<xs:annotation>
			<xs:documentation>00029</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="2"/>
				<xs:totalDigits value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!--====================================================================-->
	<!-- definition of complex elements -->
	
	<xs:complexType name="EmployerIdType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="NOSSRegistrationNbr"/>
				<xs:element ref="ProvisionalNSSONbr" minOccurs="0" maxOccurs="0"/>
				<xs:element ref="NOSSLPARegistrationNbr"/>
			</xs:choice>
			<xs:element ref="CompanyID"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="FormType">
		<xs:sequence>
			<xs:element ref="Identification"/>
			<xs:element ref="FormCreationDate"/>
			<xs:element ref="FormCreationHour"/>
			<xs:element ref="AttestationStatus"/>
			<xs:element ref="TypeForm"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="IdfluxInformationType">
		<xs:sequence>
			<xs:element ref="JustificationCode"/>
			<xs:element ref="EffectiveStartingDate"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="OutdatedSituationType">
		<xs:choice>
			<xs:sequence>
				<xs:element ref="INSS" minOccurs="0"/>
				<xs:element ref="WorkerName" minOccurs="0"/>
				<xs:element ref="WorkerFirstName" minOccurs="0"/>
				<xs:element ref="WorkerBirthdate" minOccurs="0"/>
				<xs:element ref="WorkerSex" minOccurs="0"/>
			</xs:sequence>
			<xs:element ref="NOSSRegistrationNbr"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="ReferenceType">
		<xs:sequence>
			<xs:element ref="ReferenceType"/>
			<xs:element ref="ReferenceOrigin"/>
			<xs:element ref="ReferenceNbr"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ValidSituationType">
		<xs:choice>
			<xs:sequence>
				<xs:element ref="INSS"/>
				<xs:element ref="WorkerName"/>
				<xs:element ref="WorkerFirstName"/>
				<xs:element ref="WorkerBirthdate"/>
				<xs:element ref="WorkerSex"/>
			</xs:sequence>
			<xs:element ref="NOSSRegistrationNbr"/>
		</xs:choice>
	</xs:complexType>
	
</xs:schema>

=== BartVertongen/BelgianHR/xmls/IDFLUX_20223_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<IDFLUX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IDFLUX_20223.xsd">
	<Form>
		<Identification>IDFLUX</Identification>
		<FormCreationDate>2022-09-12</FormCreationDate>
		<FormCreationHour>10:10:07.991</FormCreationHour>
		<AttestationStatus>0</AttestationStatus>
		<TypeForm>SU</TypeForm>
		<Reference>
			<ReferenceType>1</ReferenceType>
			<ReferenceOrigin>2</ReferenceOrigin>
			<ReferenceNbr>340000LKFR007</ReferenceNbr>
		</Reference>
		<IdfluxInformation>
			<JustificationCode>91</JustificationCode>
			<EffectiveStartingDate>2022-09-11</EffectiveStartingDate>
			<EmployerId>
				<NOSSRegistrationNbr>175702307</NOSSRegistrationNbr>
				<CompanyID>471149091</CompanyID>
			</EmployerId>
			<ValidSituation>
				<INSS>78070739119</INSS>
				<WorkerName>FRANS</WorkerName>
				<WorkerFirstName>ROBERT</WorkerFirstName>
				<WorkerBirthdate>1978-07-07</WorkerBirthdate>
				<WorkerSex>1</WorkerSex>
			</ValidSituation>
			<OutdatedSituation>
				<WorkerBirthdate>1970-07-07</WorkerBirthdate>
			</OutdatedSituation>
		</IdfluxInformation>
	</Form>
</IDFLUX>

=== BartVertongen/BelgianHR/xmls/IDFLUX_20223_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<IDFLUX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IDFLUX_20223.xsd">
	<Form>
		<Identification>IDFLUX</Identification>
		<FormCreationDate>2022-09-11</FormCreationDate>
		<FormCreationHour>09:28:51.544</FormCreationHour>
		<AttestationStatus>0</AttestationStatus>
		<TypeForm>SU</TypeForm>
		<Reference>
			<ReferenceType>1</ReferenceType>
			<ReferenceOrigin>2</ReferenceOrigin>
			<ReferenceNbr>340000LKFR007</ReferenceNbr>
		</Reference>
		<IdfluxInformation>
			<JustificationCode>92</JustificationCode>
			<EffectiveStartingDate>2022-07-03</EffectiveStartingDate>
			<EmployerId>
				<NOSSRegistrationNbr>131130710</NOSSRegistrationNbr>
				<CompanyID>479489311</CompanyID>
			</EmployerId>
			<ValidSituation>
				<NOSSRegistrationNbr>131130710</NOSSRegistrationNbr>
			</ValidSituation>
			<OutdatedSituation>
				<NOSSRegistrationNbr>178273680</NOSSRegistrationNbr>
			</OutdatedSituation>
		</IdfluxInformation>
	</Form>
</IDFLUX>
